export const FETCH_PAGED_DATA = 'FETCH_PAGED_DATA';

export const RECIVE_PAGED_DATA = 'RECIVE_PAGED_DATA';

export const RECIVE_BLOG_POST = 'RECIVE_BLOG_POST';

export const FETCH_ERROR_BLOG_POST = 'FETCH_ERROR_BLOG_POST';

export const THUMB_UP = 'THUMB_UP';

export const THUMB_UP_CANCEL = 'THUMB_UP_CANCEL';

export const FETCH_ACTION_ERROR = 'FETCH_ACTION_ERROR';

export const INSERT_COMMENT = 'INSERT_COMMENT';

export const ADD_BLOG_TAG_FEILTER = 'ADD_BLOG_TAG_FEILTER';

export const REMOVE_BLOG_TAG_FEILTER = 'REMOVE_BLOG_TAG_FEILTER';

export const SET_BLOG_KEYWORD_FILTER = 'SET_BLOG_KEYWORD_FILTER';

export const TOGGLE_LOGIN_CARD = 'TOGGLE_LOGIN_CARD';

export const UPDATE_USER = 'UPDATE_USER';

export const FETCH_MESSAGE = 'FETCH_MESSAGE';

export const INSERT_MESSAGE = 'INSERT_MESSAGE';

export const TOGGLE_CHATROOM = 'TOGGLE_CHATROOM';

export const CLEAR_UNREAD = 'CLEAR_UNREAD';

export const FETCH_ONLINE_USERS = 'FETCH_ONLINE_USERS';

export const ADD_ONLINE_USER = 'ADD_ONLINE_USER';

export const REMOVE_ONLINE_USER = 'REMOVE_ONLINE_USER';